# Generated by Django 3.2.5 on 2021-07-12 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('removalregister', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='removalreg',
            old_name='chittyname',
            new_name='chittyName',
        ),
    ]
